version: '3.8'

services:
  web:
    build: .
    command: gunicorn railway_project.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 120 --log-level info
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:

      - ./logs:/app/logs
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

